"""empty message

<<<<<<< HEAD:migrations/versions/5b4dd46afad4_.py
Revision ID: 5b4dd46afad4
Revises: 
Create Date: 2021-05-12 11:38:07.346668
=======
Revision ID: 407339fbadd8
Revises: 
Create Date: 2021-05-13 20:56:13.653055
>>>>>>> a14c3d27f57183a381f9901be6c8b21d17dd770c:migrations/versions/407339fbadd8_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/5b4dd46afad4_.py
revision = '5b4dd46afad4'
=======
revision = '407339fbadd8'
>>>>>>> a14c3d27f57183a381f9901be6c8b21d17dd770c:migrations/versions/407339fbadd8_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('name_region', sa.String(length=100), nullable=True),
    sa.Column('name_commune', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_service', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=90), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('name_commune', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('morning', sa.Boolean(), nullable=False),
    sa.Column('afternoon', sa.Boolean(), nullable=False),
    sa.Column('evening', sa.Boolean(), nullable=False),
    sa.Column('id_user', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=250), nullable=True),
    sa.Column('id_user', sa.String(length=30), nullable=False),
    sa.Column('id_communes', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_communes'], ['communes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profile', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'id_profile')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.Column('request_status', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=90), nullable=False),
    sa.Column('contact_phone', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('hour', sa.String(length=10), nullable=False),
    sa.Column('id_profile', sa.Integer(), nullable=True),
    sa.Column('id_service', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_profile'], ['profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('ratings')
    op.drop_table('profile')
    op.drop_table('availability')
    op.drop_table('user')
    op.drop_table('services')
    op.drop_table('communes')
    # ### end Alembic commands ###
