"""empty message

Revision ID: 821f1849abf4
Revises: 
Create Date: 2021-04-29 00:08:43.736800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821f1849abf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil',
    sa.Column('Id_Perfil', sa.Integer(), nullable=False),
    sa.Column('Rut', sa.Integer(), nullable=False),
    sa.Column('Rol', sa.String(length=15), nullable=False),
    sa.Column('Nombres', sa.String(length=60), nullable=False),
    sa.Column('Apellidos', sa.String(length=90), nullable=False),
    sa.Column('Telefono', sa.Integer(), nullable=False),
    sa.Column('Direccion', sa.String(length=150), nullable=False),
    sa.Column('Pregunta', sa.String(length=200), nullable=True),
    sa.Column('Id_Comuna', sa.Integer(), nullable=False),
    sa.Column('Comunas_Atencion', sa.String(length=200), nullable=True),
    sa.Column('Experiencia', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Id_Perfil', 'Rut', 'Id_Comuna')
    )
    op.create_table('servicios',
    sa.Column('Id_Servicio', sa.Integer(), nullable=False),
    sa.Column('Nombre_Servicio', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id_Servicio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicios')
    op.drop_table('perfil')
    # ### end Alembic commands ###
