"""empty message

Revision ID: 92c9ea1092df
Revises: 
Create Date: 2021-04-29 20:42:28.249423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c9ea1092df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunas',
    sa.Column('Id_Region', sa.Integer(), nullable=False),
    sa.Column('Id_Comuna', sa.Integer(), nullable=False),
    sa.Column('Nombre_Comuna', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('Id_Comuna')
    )
    op.create_table('perfil',
    sa.Column('Id_Perfil', sa.Integer(), nullable=False),
    sa.Column('Rut', sa.Integer(), nullable=False),
    sa.Column('Rol', sa.String(length=15), nullable=False),
    sa.Column('Nombres', sa.String(length=60), nullable=False),
    sa.Column('Apellidos', sa.String(length=90), nullable=False),
    sa.Column('Telefono', sa.Integer(), nullable=False),
    sa.Column('Direccion', sa.String(length=150), nullable=False),
    sa.Column('Pregunta', sa.String(length=100), nullable=True),
    sa.Column('Respuesta', sa.String(length=200), nullable=True),
    sa.Column('Id_Comuna', sa.Integer(), nullable=False),
    sa.Column('Comunas_Atencion', sa.String(length=200), nullable=True),
    sa.Column('Experiencia', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Id_Perfil', 'Rut', 'Id_Comuna')
    )
    op.create_table('servicios',
    sa.Column('Id_Servicio', sa.Integer(), nullable=False),
    sa.Column('Nombre_Servicio', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id_Servicio')
    )
    op.create_table('solicitudes',
    sa.Column('Id_Solicitud', sa.Integer(), nullable=False),
    sa.Column('Id_Servicio', sa.Integer(), nullable=False),
    sa.Column('Id_Perfil', sa.Integer(), nullable=False),
    sa.Column('id_Comuna', sa.Integer(), nullable=False),
    sa.Column('Estado_Solicitud', sa.String(length=10), nullable=False),
    sa.Column('Nombres', sa.String(length=60), nullable=False),
    sa.Column('Apellidos', sa.String(length=90), nullable=False),
    sa.Column('Telefono_Contacto', sa.Integer(), nullable=False),
    sa.Column('Direccion', sa.String(length=150), nullable=False),
    sa.Column('Calificacion', sa.Integer(), nullable=True),
    sa.Column('Fecha', sa.Date(), nullable=True),
    sa.Column('Hora', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Id_Solicitud', 'Id_Servicio', 'Id_Perfil', 'id_Comuna')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes')
    op.drop_table('servicios')
    op.drop_table('perfil')
    op.drop_table('comunas')
    # ### end Alembic commands ###
