"""empty message

Revision ID: d025ce61b87c
Revises: 
Create Date: 2021-05-01 23:06:36.072941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd025ce61b87c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communes',
    sa.Column('Id_Region', sa.Integer(), nullable=False),
    sa.Column('Id_Commune', sa.Integer(), nullable=False),
    sa.Column('Name_Commune', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('Id_Commune')
    )
    op.create_table('profile',
    sa.Column('Id_Profile', sa.Integer(), nullable=False),
    sa.Column('Rut', sa.Integer(), nullable=False),
    sa.Column('Rol', sa.String(length=15), nullable=False),
    sa.Column('Names', sa.String(length=60), nullable=False),
    sa.Column('Last_Name', sa.String(length=90), nullable=False),
    sa.Column('Phone', sa.Integer(), nullable=False),
    sa.Column('Address', sa.String(length=150), nullable=False),
    sa.Column('Question', sa.String(length=100), nullable=True),
    sa.Column('Answer', sa.String(length=200), nullable=True),
    sa.Column('Id_Commune', sa.Integer(), nullable=False),
    sa.Column('Attention_Communes', sa.String(length=200), nullable=True),
    sa.Column('Experience', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Id_Profile', 'Rut', 'Id_Commune')
    )
    op.create_table('services',
    sa.Column('Id_Service', sa.Integer(), nullable=False),
    sa.Column('Name_Service', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id_Service')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('profile')
    op.drop_table('communes')
    op.drop_table('availability')
    # ### end Alembic commands ###
