"""empty message

Revision ID: d321640b5ec4
Revises: 
Create Date: 2021-05-05 20:51:07.425268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd321640b5ec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id_profile', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('hour', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_profile')
    )
    op.create_table('communes',
    sa.Column('name_region', sa.String(length=100), nullable=False),
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.Column('name_commune', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_commune')
    )
    op.create_table('profile',
    sa.Column('id_profile', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('full_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=90), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.Column('attention_communes', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_profile', 'id_commune')
    )
    op.create_table('ratings',
    sa.Column('id_profile', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_profile')
    )
    op.create_table('requests',
    sa.Column('id_request', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('id_profile', sa.Integer(), nullable=False),
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.Column('request_status', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=90), nullable=False),
    sa.Column('contact_phone', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('hour', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_request')
    )
    op.create_table('services',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('name_service', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_service')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=9), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('password_previous', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('services')
    op.drop_table('requests')
    op.drop_table('ratings')
    op.drop_table('profile')
    op.drop_table('communes')
    op.drop_table('availability')
    # ### end Alembic commands ###
